sonar.projectKey=Adrian55Stack_ChatBotRxjs
sonar.organization=adrian55stack


sonar.modules=ChatBotFE,ChatBotBE

# Angular
ChatBotFE.sonar.projectName=ChatBotFE
ChatBotFE.sonar.projectBaseDir=ChatBotFE
ChatBotFE.sonar.sources=src
ChatBotFE.sonar.tests=src
ChatBotFE.sonar.test.inclusions=src/**/*.spec.ts
ChatBotFE.sonar.exclusions=src/**/*.spec.ts
ChatBotFE.sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Node.js
ChatBotBE.sonar.projectName=ChatBotBE
ChatBotBE.sonar.projectBaseDir=ChatBotBE
ChatBotBE.sonar.sources=src
ChatBotBE.sonar.tests=tests
ChatBotBE.sonar.test.inclusions=tests/**/*.test.js
ChatBotBE.sonar.exclusions=tests/**/*.test.js
ChatBotBE.sonar.javascript.lcov.reportPaths=ChatBotBE/coverage/lcov.info
ChatBotBE.sonar.inclusions=src/**/*.js
ChatBotBE.sonar.coverage.exclusions=tests/**/*.test.js
