sonar.projectKey=Adrian55Stack_ChatBotRxjs
sonar.organization=adrian55stack


sonar.modules=ChatBotFE,ChatBotBE

# Angular
ChatBotFE.sonar.projectName=ChatBotFE
ChatBotFE.sonar.sources=src
ChatBotFE.sonar.tests=src
ChatBotFE.sonar.javascript.lcov.reportPaths=coverage/lcov.info
ChatBotFE.sonar.testExecutionReportPaths=coverage/test-report.xml

# Node.js
ChatBotBE.sonar.projectName=ChatBotBE
ChatBotBE.sonar.sources=src
ChatBotBE.sonar.tests=tests
ChatBotBE.sonar.javascript.lcov.reportPaths=coverage/lcov.info
ChatBotBE.sonar.testExecutionReportPaths=coverage/test-report.xml
