sonar.projectKey=Adrian55Stack_ChatBotRxjs
sonar.organization=adrian55stack


sonar.modules=frontend,backend

# Angular
frontend.sonar.projectName=ChatBotFE
frontend.sonar.sources=ChatBotFE/src
frontend.sonar.tests=ChatBotFE/src
frontend.sonar.javascript.lcov.reportPaths=ChatBotFE/coverage/lcov.info
frontend.sonar.testExecutionReportPaths=ChatBotFE/coverage/test-report.xml

# Node.js
backend.sonar.projectName=ChatBotBE
backend.sonar.sources=ChatBotBE/src
backend.sonar.tests=ChatBotBE/tests
backend.sonar.javascript.lcov.reportPaths=ChatBotBE/coverage/lcov.info
backend.sonar.testExecutionReportPaths=ChatBotFE/coverage/test-report.xml
# backend.sonar.test.inclusions=ChatBotBE/tests/**/*.test.js
# backend.sonar.coverage.exclusions=ChatBotBE/tests/**